### ISSUE TITLE
[Bug]: README instructions for running `npm run dev` are incorrect

### ISSUE THREAD

**Issue by boldwren** [civitai/civitai#1271]
### What happened?

I just thought I would share through my experiences of walking through the setup steps outlined in README.md

I was hoping to make a minimal reproduction of #1270 locally, but it seems like there are a few pieces that are missing from this repo, that make it impossible to set up locally unless you are a civitai employee.

### Steps to reproduce the problem

1.  Clone the repo
2. Step through instructions:
    a. `npm install`
        - [ ] package-lock.json is modified, even though I set `node --version` = `v20.2.0` and `npm --version` = `9.6.6`, like in the `Dockerfile` (`node:20-alpine3.16`)
    b. `docker-compose up -d`
        - [ ] the `createbuckets` container sits there and restarts every minute or so. Would it be better to create a `scripts/setupMinio.mjs` script that spawns the appropriate `docker run` invocations only once? It could potentially also edit your `.env` file to inject the access token information.
    c. `npm run db:migrate` 
        - [ ] prompts you to create a new migration (see below). If this is intended, should the script specify a migration name instead, and then clean up after itself somehow?
    d. after running `npm run db:generate`:
        - [ ] `npm run typecheck` does not pass (see below)
    e. while running `npm run dev`:
        - [ ] opening http://localhost:3000/api/webhooks/run-jobs?token=WEBHOOK_TOKEN&run=update-metrics yields "Job not found". It feels like this could be implemented as a script that reads .env for the webhook token?
        - [ ] opening http://localhost:3000/ in an incognito window yields `error: column im.reactionCount does not exist` x3 (see below). This feels related to 
        - [ ] More errors happen if you try to create a user and go through the login flow, because NOTIFICATION_DB_URL seems to refer to a postgres database that's not managed by this repo's prisma migrations. 

### What should have happened?

See checklist items above for bugs. I'm happy to submit pull requests for some of these. I have been hacking away at creating a `STANDALONE_REPO: zc.booleanString.default(false)` in serverSchema (and maybe an equivalent in clientSchema) that can be set in order to neuter any interfaces that live in other repos.

### What platforms do you use to access the site?

MacOS

### What browsers do you use to access the site?

Mozilla Firefox, Google Chrome

### Additional information, context and logs

Contents of migration file from step 2.c. above:
```
/*
  Warnings:

  - You are about to drop the column `onboardingSteps` on the `User` table. All the data in the column will be lost.
  - You are about to drop the column `tos` on the `User` table. All the data in the column will be lost.
  - You are about to drop the `ArticleRank` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `ImageRank` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `ModelRank` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `ModelVersionRank` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `PostRank` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `TagRank` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `UserRank` table. If the table is not empty, all the data it contains will be lost.
  - Made the column `updatedAt` on table `ModelMetric` required. This step will fail if there are existing NULL values in that column.
  - Made the column `updatedAt` on table `ModelVersionMetric` required. This step will fail if there are existing NULL values in that column.
  - Made the column `userId` on table `NotificationViewed` required. This step will fail if there are existing NULL values in that column.

*/
-- DropIndex
DROP INDEX "EntityCollaborator_userId_entityType_entityId_idx";

-- DropIndex
DROP INDEX "Notification_userId_idx";

-- DropIndex
DROP INDEX "NotificationViewed_userId";

-- AlterTable
ALTER TABLE "Model" ALTER COLUMN "allowCommercialUse" SET DEFAULT ARRAY['Sell']::"CommercialUse"[];

-- AlterTable
ALTER TABLE "ModelMetric" ALTER COLUMN "updatedAt" SET NOT NULL,
ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "ModelVersionMetric" ALTER COLUMN "updatedAt" SET NOT NULL,
ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "NotificationViewed" ALTER COLUMN "userId" SET NOT NULL;

-- AlterTable
ALTER TABLE "ResourceReview" ALTER COLUMN "recommended" DROP DEFAULT;

-- AlterTable
ALTER TABLE "User" DROP COLUMN "onboardingSteps",
DROP COLUMN "tos";

-- DropTable
DROP TABLE "ArticleRank";

-- DropTable
DROP TABLE "ImageRank";

-- DropTable
DROP TABLE "ModelRank";

-- DropTable
DROP TABLE "ModelVersionRank";

-- DropTable
DROP TABLE "PostRank";

-- DropTable
DROP TABLE "TagRank";

-- DropTable
DROP TABLE "UserRank";

-- DropEnum
DROP TYPE "OnboardingStep";

-- CreateIndex
CREATE INDEX "EntityCollaborator_userId_entityType_entityId_idx" ON "EntityCollaborator"("userId", "entityType", "entityId");

-- CreateIndex
CREATE INDEX "Notification_userId_createdAt_idx" ON "Notification"("userId", "createdAt");

-- AddForeignKey
ALTER TABLE "ImageConnection" ADD CONSTRAINT "ImageConnection_imageId_fkey" FOREIGN KEY ("imageId") REFERENCES "Image"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CollectionItem" ADD CONSTRAINT "CollectionItem_articleId_fkey" FOREIGN KEY ("articleId") REFERENCES "Article"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CollectionItem" ADD CONSTRAINT "CollectionItem_postId_fkey" FOREIGN KEY ("postId") REFERENCES "Post"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CollectionItem" ADD CONSTRAINT "CollectionItem_imageId_fkey" FOREIGN KEY ("imageId") REFERENCES "Image"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CollectionItem" ADD CONSTRAINT "CollectionItem_modelId_fkey" FOREIGN KEY ("modelId") REFERENCES "Model"("id") ON DELETE CASCADE ON UPDATE CASCADE;
```

output from 2.d 
- [ ] I should make a clean clone and re-run this, because some things might be due to my patches

```
$ npm run typecheck

> model-share@4.0.14 typecheck
> tsc --noEmit

src/components/CreatorCard/CreatorCard.tsx:306:68 - error TS2551: Property 'generationCountAllTime' does not exist on type '{ uploadCountAllTime: number; downloadCountAllTime: number; ratingCountAllTime: number; followerCountAllTime: number; ratingAllTime: number; favoriteCountAllTime: number; thumbsUpCountAllTime: number; reactionCountAllTime: number; } | { downloadCountAllTime: number; thumbsUpCountAllTime: number; followerCountAllTime: number; reactionCountAllTime: number; generationCountAllTime: number; uploadCountAllTime: number; }'. Did you mean 'reactionCountAllTime'?
  Property 'generationCountAllTime' does not exist on type '{ uploadCountAllTime: number; downloadCountAllTime: number; ratingCountAllTime: number; followerCountAllTime: number; ratingAllTime: number; favoriteCountAllTime: number; thumbsUpCountAllTime: number; reactionCountAllTime: number; }'.

306                       displayStats.includes('generations') ? stats.generationCountAllTime : null
                                                                       ~~~~~~~~~~~~~~~~~~~~~~

  src/components/CreatorCard/CreatorCard.tsx:197:7
    197       reactionCountAllTime: 0,
              ~~~~~~~~~~~~~~~~~~~~~~~
    'reactionCountAllTime' is declared here.

src/components/Notifications/NotificationBell.tsx:166:17 - error TS2322: Type '(NotificationsRaw | undefined)[]' is not assignable to type 'NotificationsRaw[]'.
  Type 'NotificationsRaw | undefined' is not assignable to type 'NotificationsRaw'.
    Type 'undefined' is not assignable to type 'NotificationsRaw'.

166                 items={notifications}
                    ~~~~~

  src/components/Notifications/NotificationList.tsx:122:3
    122   items: NotificationGetAll['items'];
          ~~~~~
    The expected type comes from property 'items' which is declared here on type 'IntrinsicAttributes & Props'

src/components/Notifications/NotificationList.tsx:28:8 - error TS18048: 'items' is possibly 'undefined'.

28       {items.map((notification) => {
          ~~~~~

src/components/Notifications/NotificationList.tsx:123:59 - error TS2537: Type 'NotificationsRaw[] | undefined' has no matching index signature for type 'number'.

123   onItemClick: (notification: NotificationGetAll['items'][number], keepOpened: boolean) => void;
                                                              ~~~~~~

src/components/Notifications/notifications.utils.ts:86:34 - error TS18048: 'page.items' is possibly 'undefined'.

86               for (const item of page.items) {
                                    ~~~~~~~~~~

src/components/Notifications/notifications.utils.ts:154:11 - error TS18048: 'firstPage.items' is possibly 'undefined'.

154           firstPage.items.unshift(newUpdated);
              ~~~~~~~~~~~~~~~

src/pages/user/notifications.tsx:85:17 - error TS2322: Type '(NotificationsRaw | undefined)[]' is not assignable to type 'NotificationsRaw[]'.

85                 items={notifications}
                   ~~~~~

  src/components/Notifications/NotificationList.tsx:122:3
    122   items: NotificationGetAll['items'];
          ~~~~~
    The expected type comes from property 'items' which is declared here on type 'IntrinsicAttributes & Props'

src/server/controllers/notification.controller.ts:32:9 - error TS18048: 'items' is possibly 'undefined'.

32     if (items.length > limit) {
           ~~~~~

src/server/controllers/notification.controller.ts:33:24 - error TS18048: 'items' is possibly 'undefined'.

33       const nextItem = items.pop();
                          ~~~~~

src/types/router.ts:27:66 - error TS2537: Type 'NotificationsRaw[] | undefined' has no matching index signature for type 'number'.

27 export type NotificationGetAllItem = NotificationGetAll['items'][number];
                                                                    ~~~~~~


Found 10 errors in 7 files.

Errors  Files
     1  src/components/CreatorCard/CreatorCard.tsx:306
     1  src/components/Notifications/NotificationBell.tsx:166
     2  src/components/Notifications/NotificationList.tsx:28
     2  src/components/Notifications/notifications.utils.ts:86
     1  src/pages/user/notifications.tsx:85
     2  src/server/controllers/notification.controller.ts:32
     1  src/types/router.ts:27
```

first error from `npm run dev`:

```
❌ tRPC failed on image.getInfinite
TRPCError: An unexpected error ocurred, please try again later
    at throwDbError (webpack-internal:///(api)/./src/server/utils/errorHandling.ts:77:11)
    at getInfiniteImagesHandler (webpack-internal:///(api)/./src/server/controllers/image.controller.ts:216:94)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolveMiddleware (file:///Users/alsuren/src/civitai/node_modules/@trpc/server/dist/index.mjs:421:30)
    ... 4 lines matching cause stack trace ...
    at async callRecursive (file:///Users/alsuren/src/civitai/node_modules/@trpc/server/dist/index.mjs:451:32)
    at async resolve (file:///Users/alsuren/src/civitai/node_modules/@trpc/server/dist/index.mjs:481:24) {
  code: 'INTERNAL_SERVER_ERROR',
  [cause]: error: column im.reactionCount does not exist
      at /Users/alsuren/src/civitai/node_modules/pg-pool/index.js:45:11
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async getAllImages (webpack-internal:///(api)/./src/server/services/image.service.ts:900:34)
      at async getInfiniteImagesHandler (webpack-internal:///(api)/./src/server/controllers/image.controller.ts:203:16)
      at async resolveMiddleware (file:///Users/alsuren/src/civitai/node_modules/@trpc/server/dist/index.mjs:421:30)
      at async callRecursive (file:///Users/alsuren/src/civitai/node_modules/@trpc/server/dist/index.mjs:451:32)
      at async callRecursive (file:///Users/alsuren/src/civitai/node_modules/@trpc/server/dist/index.mjs:451:32)
      at async eval (webpack-internal:///(api)/./src/server/trpc.ts:77:20)
      at async callRecursive (file:///Users/alsuren/src/civitai/node_modules/@trpc/server/dist/index.mjs:451:32)
      at async callRecursive (file:///Users/alsuren/src/civitai/node_modules/@trpc/server/dist/index.mjs:451:32) {
    length: 116,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: '1134',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3722',
    routine: 'errorMissingColumn'
  }
}
```

**Comment by TheMysteriousPineapple** [comment]
It looks like we both might be working on exactly the same thing. Ive put a partial work around for some of the env vars which were missing

https://github.com/civitai/civitai/pull/1283

Im currently working on making an internal vs external env value that will bypass internal specific functions like captcha, stripe etc. If you have a solution already it might be advantagous to work together if you would be up for that

In reference to your point 

> opening http://localhost:3000/api/webhooks/run-jobs?token=WEBHOOK_TOKEN&run=update-metrics yields "Job not found". It feels like this could be implemented as a script that reads .env for the webhook token?

It looks like `update-metrics` function used to be a single point that ran all the update metrics. This seems to have changed to multiple individual ones. Its possible to queue the metrics by calling them one at a time for example

http://localhost:3000/api/webhooks/run-jobs?token=WEBHOOK_TOKEN&run=update-metrics-users
