### ISSUE TITLE
[Bug]: Extremely slow loading and browsing times

### ISSUE THREAD

**Issue by sergiohzph** [civitai/civitai#460]
### What happened?

Since yesterday I have only this problem with your website, page loading times become excessively slow, image previews fail. I have to reload the page several times in order to do something. I've seen that there are a lot of errors showing up in the console. Suddenly the session "closes", and all settings are lost. Until I do Ctrl + R and then it goes back to normal.

### Steps to reproduce the problem

Just do a normal browsing through the website.

### What should have happened?

The website should be fast and fluid like any other website.

### What platforms do you use to access the site?

Windows

### What browsers do you use to access the site?

Microsoft Edge

### Additional information, context and logs

```
Error #425; visit https://reactjs.org/docs/error-decoder.html?invariant=425 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Zr (framework-4ed89e9640adfb9e.js:1:43709)
    at qu (framework-4ed89e9640adfb9e.js:1:85321)
    at ks (framework-4ed89e9640adfb9e.js:1:109552)
    at bs (framework-4ed89e9640adfb9e.js:1:109433)
    at gs (framework-4ed89e9640adfb9e.js:1:109300)
    at vs (framework-4ed89e9640adfb9e.js:1:109163)
    at ls (framework-4ed89e9640adfb9e.js:1:104267)
    at S (framework-4ed89e9640adfb9e.js:1:138469)
    at MessagePort.T (framework-4ed89e9640adfb9e.js:1:139003)
Zr @ framework-4ed89e9640adfb9e.js:1
qu @ framework-4ed89e9640adfb9e.js:1
ks @ framework-4ed89e9640adfb9e.js:1
bs @ framework-4ed89e9640adfb9e.js:1
gs @ framework-4ed89e9640adfb9e.js:1
vs @ framework-4ed89e9640adfb9e.js:1
ls @ framework-4ed89e9640adfb9e.js:1
S @ framework-4ed89e9640adfb9e.js:1
T @ framework-4ed89e9640adfb9e.js:1
10framework-4ed89e9640adfb9e.js:1  
Uncaught Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at sa (framework-4ed89e9640adfb9e.js:1:48565)
    at xi (framework-4ed89e9640adfb9e.js:1:122130)
    at bs (framework-4ed89e9640adfb9e.js:1:109372)
    at gs (framework-4ed89e9640adfb9e.js:1:109300)
    at vs (framework-4ed89e9640adfb9e.js:1:109163)
    at ls (framework-4ed89e9640adfb9e.js:1:104267)
    at S (framework-4ed89e9640adfb9e.js:1:138469)
    at MessagePort.T (framework-4ed89e9640adfb9e.js:1:139003)
sa @ framework-4ed89e9640adfb9e.js:1
xi @ framework-4ed89e9640adfb9e.js:1
bs @ framework-4ed89e9640adfb9e.js:1
gs @ framework-4ed89e9640adfb9e.js:1
vs @ framework-4ed89e9640adfb9e.js:1
ls @ framework-4ed89e9640adfb9e.js:1
S @ framework-4ed89e9640adfb9e.js:1
T @ framework-4ed89e9640adfb9e.js:1
framework-4ed89e9640adfb9e.js:1  
Uncaught Error: Minified React error #422; visit https://reactjs.org/docs/error-decoder.html?invariant=422 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at framework-4ed89e9640adfb9e.js:1:79227
    at Iu (framework-4ed89e9640adfb9e.js:1:80491)
    at xi (framework-4ed89e9640adfb9e.js:1:122333)
    at bs (framework-4ed89e9640adfb9e.js:1:109372)
    at gs (framework-4ed89e9640adfb9e.js:1:109300)
    at vs (framework-4ed89e9640adfb9e.js:1:109163)
    at ls (framework-4ed89e9640adfb9e.js:1:104267)
    at S (framework-4ed89e9640adfb9e.js:1:138469)
    at MessagePort.T (framework-4ed89e9640adfb9e.js:1:139003)
(anónimo) @ framework-4ed89e9640adfb9e.js:1
Iu @ framework-4ed89e9640adfb9e.js:1
xi @ framework-4ed89e9640adfb9e.js:1
bs @ framework-4ed89e9640adfb9e.js:1
gs @ framework-4ed89e9640adfb9e.js:1
vs @ framework-4ed89e9640adfb9e.js:1
ls @ framework-4ed89e9640adfb9e.js:1
S @ framework-4ed89e9640adfb9e.js:1
T @ framework-4ed89e9640adfb9e.js:1
questions-6ec042
```
![image](https://user-images.githubusercontent.com/124453184/231774286-69b5fc2c-7984-4866-95c6-2d0387b7e57a.png)

**Comment by JustMaier** [comment]
Hey there @sergiohzph we were having trouble with the amount of traffic. We've since optimized our hardware and software to prepare for the next wave. Hopefully things will be faster for you.

The error that you mentioned is related to hydration being done by the NextJS framework. We only see it in production and we still can't figure out what is causing it, but it doesn't seem to be affecting things too negatively. Either way, it's unrelated to the slowness that you experienced.

I'm going to close this for now, but if you still have trouble, feel free to re-open this ❤️
