### ISSUE TITLE
[Bug]: Failed to create model due to Error: model category tag not found

### ISSUE THREAD

**Issue by remi-guan** [civitai/civitai#508]
### What happened?

Today, I'm updating to the newest version of this repo's `main` branch. I'm using a repo database which is old, then synced with the current schema.

When I'm creating a model, the wizard processed to the Step 2 and throwing this error when I clicked the Next button.

![image](https://user-images.githubusercontent.com/68253563/235173584-3ddfdf5b-3ef5-4e14-9130-db89b649e9a1.png)

It shows that the error was caused by the backend was trying to fetch a tag which has the type = `model category`, but it didn't find. Caused by this line of code:

![image](https://user-images.githubusercontent.com/68253563/235176215-ad8622d6-c589-4fe5-921f-59d28e14a9b8.png)

However, I don't find anywhere which creates such tag... Is there any fix on the way?

### Steps to reproduce the problem

1. Pull and sync the database with `db:migrate`.
2. Click the Upload Model button.
3. Select Category (we have some created tags already, so it has some categories to select).
4. Next step, next step, then error.

### What should have happened?

There should be somewhere to have procedures to produce the tag named `model category` to avoid such error.

### What platforms do you use to access the site?

MacOS

### What browsers do you use to access the site?

Google Chrome

### Additional information, context and logs

Error logs, backend:

```
System Tags: []
❌ tRPC failed on model.getById
TRPCError: An unexpected error ocurred, please try again later
    at throwDbError (webpack-internal:///(api)/./src/server/utils/errorHandling.ts:66:11)
    at getModelHandler (webpack-internal:///(api)/./src/server/controllers/model.controller.ts:156:93)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolveMiddleware (file:///Users/admin/Projects/xd-civitai/node_modules/@trpc/server/dist/index.mjs:416:30)
    ... 5 lines matching cause stack trace ...
    at async resolve (file:///Users/admin/Projects/xd-civitai/node_modules/@trpc/server/dist/index.mjs:480:24) {
  code: 'INTERNAL_SERVER_ERROR',
  [cause]: Error: model category tag not found
      at getCategoryTags (webpack-internal:///(api)/./src/server/services/system-cache.ts:83:33)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async getModelHandler (webpack-internal:///(api)/./src/server/controllers/model.controller.ts:108:33)
      at async resolveMiddleware (file:///Users/admin/Projects/xd-civitai/node_modules/@trpc/server/dist/index.mjs:416:30)
      at async callRecursive (file:///Users/admin/Projects/xd-civitai/node_modules/@trpc/server/dist/index.mjs:452:32)
      at async next (file:///Users/admin/Projects/xd-civitai/node_modules/@trpc/server/dist/index.mjs:460:32)
      at async callRecursive (file:///Users/admin/Projects/xd-civitai/node_modules/@trpc/server/dist/index.mjs:452:32)
      at async next (file:///Users/admin/Projects/xd-civitai/node_modules/@trpc/server/dist/index.mjs:460:32)
      at async callRecursive (file:///Users/admin/Projects/xd-civitai/node_modules/@trpc/server/dist/index.mjs:452:32)
      at async resolve (file:///Users/admin/Projects/xd-civitai/node_modules/@trpc/server/dist/index.mjs:480:24)
}
```

Frontend:

![image](https://user-images.githubusercontent.com/68253563/235174425-5f7460d3-72e2-4ece-b978-af358b0091f8.png)

**Comment by manuelurenah** [comment]
We have added updated steps to run the app locally, please refer to the README file
